### ISSUE TITLE
Oops, it looks like something went wrong. Click OK to automatically reload Skype for Web.

### ISSUE THREAD

**Issue by skliarie** [phts/firefox-web-skype#8]
Started getting the "Oops, it looks like something went wrong. Click OK to automatically reload Skype for Web." error, shows up after 1-60 seconds of opening the www.skype.com

tried to clean up cache

Not sure whether it triggered by M$ of my recent firefox upgrade to 83.0 (64-bit) (Ubuntu 20.04)

On my home computer, same setup, the problem does not occur..
![skype_went_wrong](https://user-images.githubusercontent.com/165600/100971007-cdaf6300-353e-11eb-90d3-8946847516d9.png)

**Comment by phts** [comment]
Yeah. Duplicate of #7 

Unfortunately I cannot reproduce it and it seems to occur due to some weird logic of Skype for some users. And unfortunately most likely I cannot fix it by this extension.

I will also try to update user agent to simulate latest chrome. Maybe there is logic related to it.

**Comment by phts** [comment]
@skliarie also try to disable `security.csp.enable` in the `about:config` menu to make those failed requests working (due to Content Security Policy).

Maybe this is a reason. FF blocks them for some reason on your env. If this helps you can keep this option disabled (but this very unsafe), or you can use extension [Laboratory (Content Security Policy / CSP Toolkit)](https://addons.mozilla.org/ru/firefox/addon/laboratory-by-mozilla/) which can disable CSP for exact site (I didn't tried it by myself, so not sure).

**Comment by Faelights** [comment]
Hi, I've been getting this error, too, and I use Sidebery so I tried opening Web Skype in a different container from usual but still in the same window, and... the error did not pop up!

Not sure if this info will help pinpoint what is going on, but thought I would share in case it helps.

**Comment by drougas** [comment]
I have never used this extension, but simply the user-agent switcher which worked fine until recently, when I started seeing the Oops message. I managed to solve the problem. Steps:

1) Erase cookies of these domains and all their subdomains:

- live.com
- live.net
- microsoft.com
- microsoftonline.com
- skype.com
- skypeassets.com

2) Use Tools -> Clear Recent History to erase Cache, Offline Website Data and Active Logins.

3) Add the domains __and subdomains__ from step 1 to the UA switcher. I just added rules to switch the UA for *.skype.com etc...

3) Log in to Skype.

Everything works smoothly so far. After logging in to Skype, there's cookies from these domains:

- login.live.com
- live.com
- asm.skype.com
- login.skype.com
- skype.com
- skypeassets.com

Hope it helps...

**Comment by phts** [comment]
@drougas thank you for the info!

I also updated the extension to include those URLs - v0.6.0

**Comment by skliarie** [comment]
Tried below, nothing helped:
* security.csp.enable=false
* delete cookies
* logout/login
* disable all extensions

**Comment by skliarie** [comment]
I found some caching issue specific to FF 83, seems to be related:
https://bugzilla.mozilla.org/show_bug.cgi?id=1678243

**Comment by phts** [comment]
> I found some caching issue specific to FF 83, seems to be related:

It seems to be already fixed in 84. Try to install 84 nightly version and check.

**Comment by drougas** [comment]
Sorry, I had missed some details. I had cleaned, cookies, cache, offline website data and active logins in step 1...

**Comment by skliarie** [comment]
firefox 84 resolved the problem, closing

**Comment by pintassilgo** [comment]
Just commenting here because it may help someone.

I was still getting "Oops" message and being denied to access Skype Web. After detailed tests, I found out it's because of `geo.enabled = false`. Maybe someone else did that too to enhance privacy. Disabling this pref tells web that your browser doesn't support Geolocation API.

Instead, we should use `permissions.default.geo = 2` to block by default and not receive access request. So websites will know your browser supports Geolocation API but also that you haven't granted permission for them to access your location. This is enough to enable Skype Web for Firefox (but spoofing the user-agent is still a must).

P.S.: I only spoof UA for skype.com, I don't think it's needed for any other domain like live.com, live.net, microsoft.com, microsoftonline.com and skypeassets.com.

**Comment by Martyn575** [comment]
I can confirm that this is still an issue. It appears within seconds of loading web skype. You can't do anything because the error message steals all the mouse and keyboard focus. 

You have to click okay, which reloads the link. You log back in and it's okay for 2 maybe 3 minutes and then the error re-appears. 

Skype is completely unusable in this state, is there anything anyone can do to fix it?

**Comment by Martyn575** [comment]
Just to add something here, this has started happening suddenly over the last 5-6 days, and it's happening relentlessly and constantly, it's not working at all.

**Comment by jayur** [comment]
Yes, I have been having this issue for the past few weeks. Its not working at all because of  this message and the reloading

**Comment by Martyn575** [comment]
This is still going on, it's also going wrong in Chromium too.

**Comment by jherazob** [comment]
I've never used this extension, have been using Web Skype on Chrome/Chromium for a while, no less than a year or two. The last couple of weeks i've had this exact issue frequently. Today has been pretty bad, i've had this happen 5 times this morning. So i bet it's something not directly related to the extension or even Firefox, but it's a problem on Skype Web itself.

**Comment by phts** [comment]
Anyways, cannot reproduce so far...

**Comment by Martyn575** [comment]
I think this is a serious problem with Skype.

**Comment by akhiljalagam** [comment]
I am able to resolve this issue on my firefox-114.0_1 by disabling the extension "Swift Selection Search" pop-up.  

"Swift Selection Search" settings:
![image](https://github.com/phts/firefox-web-skype/assets/21128035/e723eb53-0001-45d8-9c72-ad718a85706a)
